apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  labels:
    app: karsajobs-ui 
spec:
  replicas: 2 
  selector:
    matchLabels: 
      app: karsajobs-ui 
  template: 
    metadata:
      labels:
        app: karsajobs-ui
    spec: 
      containers:
        - name: karsajobs-ui
          image: dodysetiawan/karsajobs-ui
          ports:
            - containerPort: 8000 
          env:
            - name: VUE_APP_BACKEND
              value: http://192.168.39.40:31539