apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs-ui
  name: karsajobs-ui-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: karsajobs-ui
  type: NodePort