# versi Docker Compose
version: "3.7"


services:

  item-app:

    # base image yang digunakan
    image: node:14

    command: sh -c "yarn install && yarn run dev"

    # port mapping untuk port aplikasi dan port di host
    ports:

      - 80:8080

    # letak dari working directory
    working_dir: /app

    # environment database mongo db untuk item-app
    environment:

      MONGO_HOST: item-db

      MONGO_USER: root

      MONGO_PASSWORD: dody

      MONGO_DB: item-db
    
    # restart policy untuk item-app
    deploy:

      restart_policy:

        condition: on-failure

        delay: 5s

        max_attempts: 3

        window: 120s


  item-db:

    # base image yang digunakan
    image: mongo:3

    # volume yang digunakan di item-db
    volumes:

      - app-db:/data/db

    # environment di database mongo db
    environment:

      MONGO_ROOT_PASSWORD: dody

      MONGO_DATABASE: item-db


volumes:

  app-db: