version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq_container'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  shipping-service:
    image: dodysetiawan/shipping-service
    container_name: 'shipping-service'
    ports:
      - 3001:3001
    depends_on:
      - "rabbitmq"
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://localhost:5672
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge